# Generated by Django 6.0.7 on 2026-08-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='created_at',
        ),
    ]
