# Generated by Django 6.0.7 on 2026-08-06 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_remove_chatsession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 6, 22, 44, 12, 344152, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
