# Generated by Django 6.0.7 on 2026-08-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='expandable',
            field=models.BooleanField(default=True),
        ),
    ]
