# Generated by Django 6.0.7 on 2026-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_subtask_expandable'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timer_elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
