# Generated by Django 6.0.7 on 2026-08-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
        ('tasks', '0002_subtask_expandable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.subtask'),
        ),
    ]
